title: Xiao Qi's Homepage
page-top-title: Xiao Qi
top-section-bg-text: Computational Mathematics
home-subtitle: Xiao Qi&ensp;|&ensp;戚啸
copyright-text: '&copy; Xiao Qi 2024-2025. All Rights Reserved.'
